version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=production
      - GIPHY_API_KEY=${GIPHY_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production