version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
      # Prevent node_modules from being overwritten by the host volume
      - /app/node_modules 
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=development
    command: nodemon src/server.ts
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      # Prevent node_modules from being overwritten by the host volume
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3001/api  # For browser access
    networks:
      - app-network

networks:
  app-network:
    driver: bridge